### ISSUE TITLE
Polygon Mumbai possible?

### ISSUE THREAD

**Issue by creazy231** [MysticRyuujin/dappnode-polygon#3]
is it possible to setup a testenet node on matic mumbai in any way?

**Comment by MysticRyuujin** [comment]
I don't know what steps are required to run mumbai...because it's not documented (shocking, I know)

If I had to guess I'd say you'd need to:

1. Use the mumbai genesis files
2. Use the mumbai seeds/bootnodes
3. Use the mumbai snapshots, if they exist?
4. Use the mumbai chain-id

Now where that genesis file is I'm not sure I assume it's in their github somewhere, and the seeds/bootnodes I'm not sure about either because the seeds are provided in their documentation, but they only have documentation for mainnet (that I can see).

**Comment by creazy231** [comment]
okay so forking and change files / data to mumbai should work exactly the same regarding the instructions?

**Comment by creazy231** [comment]
maybe I'll find some time to test things out :)

**Comment by MysticRyuujin** [comment]
Theoretically, if you figure out the genesis file, seeds/bootnodes, and what version to checkout for bor and heimdall, it should work just fine...

chain-id for mumbai is `80001`

**Comment by MysticRyuujin** [comment]
Genesis files appear to be here:

https://github.com/maticnetwork/launch/blob/master/testnet-v4/without-sentry/heimdall/config/genesis.json

https://github.com/maticnetwork/launch/blob/master/testnet-v4/without-sentry/bor/genesis.json

**Comment by creazy231** [comment]
Yea I have all these information from several documentations and forum posts. Just wanted to ask if this should be possible theoretically.
I never worked with dappernode before because my company works on L2 First so Polygon is the way to go. But since DapperNode had no package for Polygon I didn't take a look into it for a long time.

**Comment by creazy231** [comment]
Latest Snapshot is here: https://forum.matic.network/t/blockchain-snapshots-april/784

**Comment by MysticRyuujin** [comment]
Nice. I'll leave this issue open in case other people come poking around.

**Comment by ASHKARAN** [comment]
you can find the latest updates here
[https://github.com/maticnetwork/launch](https://github.com/maticnetwork/launch)

I just used configuration files from this repository and everything works fine
